# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatify < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.1.0/Chatify_Darwin_x86_64.tar.gz"
      sha256 "1c61eeef75ab6c363c9aa563c36fdd36efea128a5f82a16c68422228cf499310"

      def install
        bin.install "Chatify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.1.0/Chatify_Darwin_arm64.tar.gz"
      sha256 "594cac2dd7a38b4d0733ebcae9640febb893687dbd6c7011573fc269afe95c43"

      def install
        bin.install "Chatify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.1.0/Chatify_Linux_x86_64.tar.gz"
      sha256 "106f5e504976a86b2d32090a1d889c6e172f2957cd8e9a43c0f06b892994675f"

      def install
        bin.install "Chatify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.1.0/Chatify_Linux_arm64.tar.gz"
      sha256 "3c082af48b3aed4ce03bb8d0fef73425753168aa6fcc1cbfb8221474c24e1d75"

      def install
        bin.install "Chatify"
      end
    end
  end
end
