# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatify < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.0.0/Chatify_Darwin_x86_64.tar.gz"
      sha256 "5e5d7fa86cd613f77fd08bc101da21c8a5e3374ac339bc5cca7175d46d4a24ee"

      def install
        bin.install "Chatify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.0.0/Chatify_Darwin_arm64.tar.gz"
      sha256 "8f07f83317c70b47fb206e547a69ad6729ac3d01efc4a152c5feaa730de08cb7"

      def install
        bin.install "Chatify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.0.0/Chatify_Linux_x86_64.tar.gz"
      sha256 "6090394154a8cb3b3e6ea3511e82eb4b4cf29b310aeaeb985769b34e2e45aec9"

      def install
        bin.install "Chatify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/Chatify/releases/download/v1.0.0/Chatify_Linux_arm64.tar.gz"
      sha256 "06fbc81566d467ff05252afddeaf6bef2bbbc3457dc0d596ae5412217c25b08f"

      def install
        bin.install "Chatify"
      end
    end
  end
end
