# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goit < Formula
  desc ""
  homepage ""
  version "1.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.6.0/Goit_Darwin_x86_64.tar.gz"
      sha256 "e93eb2d8adcf84ab5af85a0edc0748811887acc6210e9be51d2b9376c5f81916"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.6.0/Goit_Darwin_arm64.tar.gz"
      sha256 "45cc2b7bfd169fe03012317be1587d4e7290033a61b8cd0956d20e65c9c43d6f"

      def install
        bin.install "Goit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.6.0/Goit_Linux_x86_64.tar.gz"
      sha256 "33bbceb4eba7e4a248991568848a012d19112b96889455c46ea71ed7295c6f46"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.6.0/Goit_Linux_arm64.tar.gz"
      sha256 "0bbe48c79e678175f5c99e6d246df01ffb1e3536dc36e468ec586c37eb0f97c9"

      def install
        bin.install "Goit"
      end
    end
  end
end
