# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goit < Formula
  desc ""
  homepage ""
  version "1.7.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.7.1/Goit_Darwin_arm64.tar.gz"
      sha256 "84eea53699274225a65f0413bd9e2cef7e443c48fe877beb3f6832b3ce52158d"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.7.1/Goit_Darwin_x86_64.tar.gz"
      sha256 "f17e892aed37c46c069fc71d237ae264372b82ac5f8b7b34a7b26d4f100e56bb"

      def install
        bin.install "Goit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.7.1/Goit_Linux_arm64.tar.gz"
      sha256 "8b9a35a2af1a99b663e2820a766c03aa239a6c77dc809154248c02204d706b59"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.7.1/Goit_Linux_x86_64.tar.gz"
      sha256 "c0a70667ec76881188e5aa4e4643e5668e96f99e8fce522ee7afb6bd74e064ce"

      def install
        bin.install "Goit"
      end
    end
  end
end
