# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goit < Formula
  desc ""
  homepage ""
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.3.0/Goit_Darwin_arm64.tar.gz"
      sha256 "5f75f21a547621bd358f48bba87ca101d88240334c4d7288d9931bc875f0bb21"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.3.0/Goit_Darwin_x86_64.tar.gz"
      sha256 "ff8423bf09399db85e49a27534e3fd8de31da9d434c81c69dba72d050f792017"

      def install
        bin.install "Goit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.3.0/Goit_Linux_x86_64.tar.gz"
      sha256 "f23e26f904bc7ba9aafd7cc92dccf7eecc8126f4c05cd3e8a197304878efa481"

      def install
        bin.install "Goit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/Goit/releases/download/v1.3.0/Goit_Linux_arm64.tar.gz"
      sha256 "ce13cc8191e377b1d4c5e7eb0e004804daff69a67d5484f716639daaa388c946"

      def install
        bin.install "Goit"
      end
    end
  end
end
