# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsop < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/JunNishimura/JSOP/releases/download/v1.0.0/JSOP_Darwin_x86_64.tar.gz"
      sha256 "a869b2b61c5aa119d03c04013a680392b61a53620d32c6f5412a61683d1562fa"

      def install
        bin.install "JSOP"
      end
    end
    on_arm do
      url "https://github.com/JunNishimura/JSOP/releases/download/v1.0.0/JSOP_Darwin_arm64.tar.gz"
      sha256 "e99db5c5fb51bbb8a90207e259ae2e963a4f0b145604db4a13a4f646f5d35b01"

      def install
        bin.install "JSOP"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JunNishimura/JSOP/releases/download/v1.0.0/JSOP_Linux_x86_64.tar.gz"
        sha256 "aeff5354fb0c611847807e5b324d403d78f0c76a859158ee5eb40f6644c0df84"

        def install
          bin.install "JSOP"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JunNishimura/JSOP/releases/download/v1.0.0/JSOP_Linux_arm64.tar.gz"
        sha256 "e97504ec9b44fd1903547b51c51c75f4b7c38cd20f87e9599d6ac014fdb1cba3"

        def install
          bin.install "JSOP"
        end
      end
    end
  end
end
