# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsop < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/JunNishimura/JSOP/releases/download/v1.1.0/JSOP_Darwin_x86_64.tar.gz"
      sha256 "9943614be3d27368c52a8fc0fded20e415a41d68fcd25211cb2198482779f86d"

      def install
        bin.install "JSOP"
      end
    end
    on_arm do
      url "https://github.com/JunNishimura/JSOP/releases/download/v1.1.0/JSOP_Darwin_arm64.tar.gz"
      sha256 "8eaff89487c3b06328de010abdeb51b461d7c1d15cd886b936972eb1d1684481"

      def install
        bin.install "JSOP"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JunNishimura/JSOP/releases/download/v1.1.0/JSOP_Linux_x86_64.tar.gz"
        sha256 "71a5369c73d8bcaadd786ad965f02e814f0c81583d5116b84855ddbab30e6fbf"

        def install
          bin.install "JSOP"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JunNishimura/JSOP/releases/download/v1.1.0/JSOP_Linux_arm64.tar.gz"
        sha256 "57869198059e1833daac3b1fbfb302b84e694897f30993718a26561a81c81d1a"

        def install
          bin.install "JSOP"
        end
      end
    end
  end
end
