# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konmari < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JunNishimura/konmari/releases/download/v0.0.2/konmari_Darwin_arm64.tar.gz"
      sha256 "2c46d5cb2c1fcade2faa1334570187b342529e3fda0fb3f59a7d6acf6fc2db3f"

      def install
        bin.install "konmari"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/konmari/releases/download/v0.0.2/konmari_Darwin_x86_64.tar.gz"
      sha256 "4e3329ea4405098304804910bdc1ef5dcc0a247b6610ec7b8ff8e1ac665bcf83"

      def install
        bin.install "konmari"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JunNishimura/konmari/releases/download/v0.0.2/konmari_Linux_x86_64.tar.gz"
      sha256 "4afbace3b8a0a50e58bc9e14d91f34ee286dd7501122c980a510d1cfec3182d1"

      def install
        bin.install "konmari"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JunNishimura/konmari/releases/download/v0.0.2/konmari_Linux_arm64.tar.gz"
      sha256 "8e9245a08aa3b7a4c941ae707a887267e881f11274039487270028b33dddafd5"

      def install
        bin.install "konmari"
      end
    end
  end
end
