# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okyo < Formula
  desc ""
  homepage ""
  version "1.0.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/JunNishimura/okyo/releases/download/v1.0.1/okyo_Darwin_x86_64.tar.gz"
    sha256 "fce3a032480db820a3fe34f540c705873be384e6ecca473eb91dbe1cf18b96f9"

    def install
      bin.install "okyo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/JunNishimura/okyo/releases/download/v1.0.1/okyo_Darwin_arm64.tar.gz"
    sha256 "876cd4f21f0252080d23b79b9ca98d0de62aac1b9577a430b4d023db4486eb7a"

    def install
      bin.install "okyo"
    end
  end
end
